#=========================================================================
# Travis CI Configuration
#=========================================================================

language: c

#-------------------------------------------------------------------------
# install
#-------------------------------------------------------------------------
# We need to do a hack to make gcc default to
# gcc-6. Normally we would just set the CC/CXX environment variables, but
# we are not using them to simplify the Makefile we give students.

install:
  - sudo mkdir -p /classes/ece2400/mnist
  - sudo chown travis:travis  /classes/ece2400/mnist
  - cd /classes/ece2400/mnist
  - wget https://github.com/ece2400/ece2400-mnist-travisci-cache/raw/master/mnist.tar.gz
  - tar -xvf mnist.tar.gz

#-------------------------------------------------------------------------
# script
#-------------------------------------------------------------------------
# Show the installed files

script:
  - pwd
  - ls /classes/ece2400/mnist
  - echo "done"

